package org.bumblebee.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.bumblebee.entity.Roomuser;
import org.bumblebee.entity.RoomuserExample;

public interface RoomuserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomuser
     *
     * @mbggenerated Sat Sep 22 20:07:34 CST 2018
     */
    int countByExample(RoomuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomuser
     *
     * @mbggenerated Sat Sep 22 20:07:34 CST 2018
     */
    int deleteByExample(RoomuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomuser
     *
     * @mbggenerated Sat Sep 22 20:07:34 CST 2018
     */
    int deleteByPrimaryKey(Integer raId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomuser
     *
     * @mbggenerated Sat Sep 22 20:07:34 CST 2018
     */
    int insert(Roomuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomuser
     *
     * @mbggenerated Sat Sep 22 20:07:34 CST 2018
     */
    int insertSelective(Roomuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomuser
     *
     * @mbggenerated Sat Sep 22 20:07:34 CST 2018
     */
    List<Roomuser> selectByExample(RoomuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomuser
     *
     * @mbggenerated Sat Sep 22 20:07:34 CST 2018
     */
    Roomuser selectByPrimaryKey(Integer raId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomuser
     *
     * @mbggenerated Sat Sep 22 20:07:34 CST 2018
     */
    int updateByExampleSelective(@Param("record") Roomuser record, @Param("example") RoomuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomuser
     *
     * @mbggenerated Sat Sep 22 20:07:34 CST 2018
     */
    int updateByExample(@Param("record") Roomuser record, @Param("example") RoomuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomuser
     *
     * @mbggenerated Sat Sep 22 20:07:34 CST 2018
     */
    int updateByPrimaryKeySelective(Roomuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomuser
     *
     * @mbggenerated Sat Sep 22 20:07:34 CST 2018
     */
    int updateByPrimaryKey(Roomuser record);
}