package org.bumblebee.dao;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.bumblebee.entity.Sigindetail;
import org.bumblebee.entity.SigindetailExample;
import org.springframework.stereotype.Component;

@Mapper
@Component
public interface SigindetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sigindetail
     *
     * @mbggenerated Tue Sep 25 20:06:45 CST 2018
     */
    int countByExample(SigindetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sigindetail
     *
     * @mbggenerated Tue Sep 25 20:06:45 CST 2018
     */
    int deleteByExample(SigindetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sigindetail
     *
     * @mbggenerated Tue Sep 25 20:06:45 CST 2018
     */
    int deleteByPrimaryKey(Integer sdId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sigindetail
     *
     * @mbggenerated Tue Sep 25 20:06:45 CST 2018
     */
    int insert(Sigindetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sigindetail
     *
     * @mbggenerated Tue Sep 25 20:06:45 CST 2018
     */
    int insertSelective(Sigindetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sigindetail
     *
     * @mbggenerated Tue Sep 25 20:06:45 CST 2018
     */
    List<Sigindetail> selectByExample(SigindetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sigindetail
     *
     * @mbggenerated Tue Sep 25 20:06:45 CST 2018
     */
    Sigindetail selectByPrimaryKey(Integer sdId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sigindetail
     *
     * @mbggenerated Tue Sep 25 20:06:45 CST 2018
     */
    int updateByExampleSelective(@Param("record") Sigindetail record, @Param("example") SigindetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sigindetail
     *
     * @mbggenerated Tue Sep 25 20:06:45 CST 2018
     */
    int updateByExample(@Param("record") Sigindetail record, @Param("example") SigindetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sigindetail
     *
     * @mbggenerated Tue Sep 25 20:06:45 CST 2018
     */
    int updateByPrimaryKeySelective(Sigindetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sigindetail
     *
     * @mbggenerated Tue Sep 25 20:06:45 CST 2018
     */
    int updateByPrimaryKey(Sigindetail record);

    List<Sigindetail> selectExtendUserByExample(SigindetailExample example);
}