package org.bumblebee.dao;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.bumblebee.entity.Sigin;
import org.bumblebee.entity.SiginExample;
import org.springframework.stereotype.Component;

@Mapper
@Component
public interface SiginMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sigin
     *
     * @mbggenerated Tue Sep 25 20:06:45 CST 2018
     */
    int countByExample(SiginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sigin
     *
     * @mbggenerated Tue Sep 25 20:06:45 CST 2018
     */
    int deleteByExample(SiginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sigin
     *
     * @mbggenerated Tue Sep 25 20:06:45 CST 2018
     */
    int deleteByPrimaryKey(Integer siginId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sigin
     *
     * @mbggenerated Tue Sep 25 20:06:45 CST 2018
     */
    int insert(Sigin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sigin
     *
     * @mbggenerated Tue Sep 25 20:06:45 CST 2018
     */
    int insertSelective(Sigin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sigin
     *
     * @mbggenerated Tue Sep 25 20:06:45 CST 2018
     */
    List<Sigin> selectByExample(SiginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sigin
     *
     * @mbggenerated Tue Sep 25 20:06:45 CST 2018
     */
    Sigin selectByPrimaryKey(Integer siginId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sigin
     *
     * @mbggenerated Tue Sep 25 20:06:45 CST 2018
     */
    int updateByExampleSelective(@Param("record") Sigin record, @Param("example") SiginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sigin
     *
     * @mbggenerated Tue Sep 25 20:06:45 CST 2018
     */
    int updateByExample(@Param("record") Sigin record, @Param("example") SiginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sigin
     *
     * @mbggenerated Tue Sep 25 20:06:45 CST 2018
     */
    int updateByPrimaryKeySelective(Sigin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sigin
     *
     * @mbggenerated Tue Sep 25 20:06:45 CST 2018
     */
    int updateByPrimaryKey(Sigin record);

    List<Sigin> selectExtendByExample(SiginExample example);
}