package org.bumblebee.dao;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.bumblebee.entity.Votedetail;
import org.bumblebee.entity.VotedetailExample;
import org.springframework.stereotype.Component;

@Mapper
@Component
public interface VotedetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votedetail
     *
     * @mbggenerated Tue Sep 25 20:06:45 CST 2018
     */
    int countByExample(VotedetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votedetail
     *
     * @mbggenerated Tue Sep 25 20:06:45 CST 2018
     */
    int deleteByExample(VotedetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votedetail
     *
     * @mbggenerated Tue Sep 25 20:06:45 CST 2018
     */
    int deleteByPrimaryKey(Integer vdId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votedetail
     *
     * @mbggenerated Tue Sep 25 20:06:45 CST 2018
     */
    int insert(Votedetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votedetail
     *
     * @mbggenerated Tue Sep 25 20:06:45 CST 2018
     */
    int insertSelective(Votedetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votedetail
     *
     * @mbggenerated Tue Sep 25 20:06:45 CST 2018
     */
    List<Votedetail> selectByExample(VotedetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votedetail
     *
     * @mbggenerated Tue Sep 25 20:06:45 CST 2018
     */
    Votedetail selectByPrimaryKey(Integer vdId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votedetail
     *
     * @mbggenerated Tue Sep 25 20:06:45 CST 2018
     */
    int updateByExampleSelective(@Param("record") Votedetail record, @Param("example") VotedetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votedetail
     *
     * @mbggenerated Tue Sep 25 20:06:45 CST 2018
     */
    int updateByExample(@Param("record") Votedetail record, @Param("example") VotedetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votedetail
     *
     * @mbggenerated Tue Sep 25 20:06:45 CST 2018
     */
    int updateByPrimaryKeySelective(Votedetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votedetail
     *
     * @mbggenerated Tue Sep 25 20:06:45 CST 2018
     */
    int updateByPrimaryKey(Votedetail record);
}