package org.bumblebee.dao;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.bumblebee.entity.Voterecord;
import org.bumblebee.entity.VoterecordExample;
import org.springframework.stereotype.Component;

@Mapper
@Component
public interface VoterecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voterecord
     *
     * @mbggenerated Wed Sep 26 10:53:26 CST 2018
     */
    int countByExample(VoterecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voterecord
     *
     * @mbggenerated Wed Sep 26 10:53:26 CST 2018
     */
    int deleteByExample(VoterecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voterecord
     *
     * @mbggenerated Wed Sep 26 10:53:26 CST 2018
     */
    int deleteByPrimaryKey(Integer vrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voterecord
     *
     * @mbggenerated Wed Sep 26 10:53:26 CST 2018
     */
    int insert(Voterecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voterecord
     *
     * @mbggenerated Wed Sep 26 10:53:26 CST 2018
     */
    int insertSelective(Voterecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voterecord
     *
     * @mbggenerated Wed Sep 26 10:53:26 CST 2018
     */
    List<Voterecord> selectByExample(VoterecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voterecord
     *
     * @mbggenerated Wed Sep 26 10:53:26 CST 2018
     */
    Voterecord selectByPrimaryKey(Integer vrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voterecord
     *
     * @mbggenerated Wed Sep 26 10:53:26 CST 2018
     */
    int updateByExampleSelective(@Param("record") Voterecord record, @Param("example") VoterecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voterecord
     *
     * @mbggenerated Wed Sep 26 10:53:26 CST 2018
     */
    int updateByExample(@Param("record") Voterecord record, @Param("example") VoterecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voterecord
     *
     * @mbggenerated Wed Sep 26 10:53:26 CST 2018
     */
    int updateByPrimaryKeySelective(Voterecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voterecord
     *
     * @mbggenerated Wed Sep 26 10:53:26 CST 2018
     */
    int updateByPrimaryKey(Voterecord record);
}