package org.bumblebee.entity;

import java.io.Serializable;

public class Admin implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.admin_id
     *
     * @mbggenerated Sat Sep 15 16:03:14 CST 2018
     */
    private Integer adminId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.admin_account
     *
     * @mbggenerated Sat Sep 15 16:03:14 CST 2018
     */
    private String adminAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.admin_password
     *
     * @mbggenerated Sat Sep 15 16:03:14 CST 2018
     */
    private String adminPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.admin_username
     *
     * @mbggenerated Sat Sep 15 16:03:14 CST 2018
     */
    private String adminUsername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.admin_img
     *
     * @mbggenerated Sat Sep 15 16:03:14 CST 2018
     */
    private String adminImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table admin
     *
     * @mbggenerated Sat Sep 15 16:03:14 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.admin_id
     *
     * @return the value of admin.admin_id
     *
     * @mbggenerated Sat Sep 15 16:03:14 CST 2018
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.admin_id
     *
     * @param adminId the value for admin.admin_id
     *
     * @mbggenerated Sat Sep 15 16:03:14 CST 2018
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.admin_account
     *
     * @return the value of admin.admin_account
     *
     * @mbggenerated Sat Sep 15 16:03:14 CST 2018
     */
    public String getAdminAccount() {
        return adminAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.admin_account
     *
     * @param adminAccount the value for admin.admin_account
     *
     * @mbggenerated Sat Sep 15 16:03:14 CST 2018
     */
    public void setAdminAccount(String adminAccount) {
        this.adminAccount = adminAccount == null ? null : adminAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.admin_password
     *
     * @return the value of admin.admin_password
     *
     * @mbggenerated Sat Sep 15 16:03:14 CST 2018
     */
    public String getAdminPassword() {
        return adminPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.admin_password
     *
     * @param adminPassword the value for admin.admin_password
     *
     * @mbggenerated Sat Sep 15 16:03:14 CST 2018
     */
    public void setAdminPassword(String adminPassword) {
        this.adminPassword = adminPassword == null ? null : adminPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.admin_username
     *
     * @return the value of admin.admin_username
     *
     * @mbggenerated Sat Sep 15 16:03:14 CST 2018
     */
    public String getAdminUsername() {
        return adminUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.admin_username
     *
     * @param adminUsername the value for admin.admin_username
     *
     * @mbggenerated Sat Sep 15 16:03:14 CST 2018
     */
    public void setAdminUsername(String adminUsername) {
        this.adminUsername = adminUsername == null ? null : adminUsername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.admin_img
     *
     * @return the value of admin.admin_img
     *
     * @mbggenerated Sat Sep 15 16:03:14 CST 2018
     */
    public String getAdminImg() {
        return adminImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.admin_img
     *
     * @param adminImg the value for admin.admin_img
     *
     * @mbggenerated Sat Sep 15 16:03:14 CST 2018
     */
    public void setAdminImg(String adminImg) {
        this.adminImg = adminImg == null ? null : adminImg.trim();
    }
}