package org.bumblebee.entity;

import java.io.Serializable;

public class Roomuser implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roomuser.ra_id
     *
     * @mbggenerated Sat Sep 22 20:07:34 CST 2018
     */
    private Integer raId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roomuser.ra_room_id
     *
     * @mbggenerated Sat Sep 22 20:07:34 CST 2018
     */
    private Integer raRoomId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roomuser.ra_user_id
     *
     * @mbggenerated Sat Sep 22 20:07:34 CST 2018
     */
    private Integer raUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table roomuser
     *
     * @mbggenerated Sat Sep 22 20:07:34 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomuser.ra_id
     *
     * @return the value of roomuser.ra_id
     *
     * @mbggenerated Sat Sep 22 20:07:34 CST 2018
     */
    public Integer getRaId() {
        return raId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomuser.ra_id
     *
     * @param raId the value for roomuser.ra_id
     *
     * @mbggenerated Sat Sep 22 20:07:34 CST 2018
     */
    public void setRaId(Integer raId) {
        this.raId = raId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomuser.ra_room_id
     *
     * @return the value of roomuser.ra_room_id
     *
     * @mbggenerated Sat Sep 22 20:07:34 CST 2018
     */
    public Integer getRaRoomId() {
        return raRoomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomuser.ra_room_id
     *
     * @param raRoomId the value for roomuser.ra_room_id
     *
     * @mbggenerated Sat Sep 22 20:07:34 CST 2018
     */
    public void setRaRoomId(Integer raRoomId) {
        this.raRoomId = raRoomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomuser.ra_user_id
     *
     * @return the value of roomuser.ra_user_id
     *
     * @mbggenerated Sat Sep 22 20:07:34 CST 2018
     */
    public Integer getRaUserId() {
        return raUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomuser.ra_user_id
     *
     * @param raUserId the value for roomuser.ra_user_id
     *
     * @mbggenerated Sat Sep 22 20:07:34 CST 2018
     */
    public void setRaUserId(Integer raUserId) {
        this.raUserId = raUserId;
    }
}