package org.bumblebee.entity;

import java.io.Serializable;
import java.util.Date;

public class Room implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.room_id
     *
     * @mbggenerated Sat Sep 15 16:03:14 CST 2018
     */
    private Integer roomId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.room_name
     *
     * @mbggenerated Sat Sep 15 16:03:14 CST 2018
     */
    private String roomName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.room_state
     *
     * @mbggenerated Sat Sep 15 16:03:14 CST 2018
     */
    private String roomState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.room_create_id
     *
     * @mbggenerated Sat Sep 15 16:03:14 CST 2018
     */
    private Integer roomCreateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.room_create_time
     *
     * @mbggenerated Sat Sep 15 16:03:14 CST 2018
     */
    private Date roomCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.room_limit
     *
     * @mbggenerated Sat Sep 15 16:03:14 CST 2018
     */
    private Integer roomLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table room
     *
     * @mbggenerated Sat Sep 15 16:03:14 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.room_id
     *
     * @return the value of room.room_id
     *
     * @mbggenerated Sat Sep 15 16:03:14 CST 2018
     */
    public Integer getRoomId() {
        return roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.room_id
     *
     * @param roomId the value for room.room_id
     *
     * @mbggenerated Sat Sep 15 16:03:14 CST 2018
     */
    public void setRoomId(Integer roomId) {
        this.roomId = roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.room_name
     *
     * @return the value of room.room_name
     *
     * @mbggenerated Sat Sep 15 16:03:14 CST 2018
     */
    public String getRoomName() {
        return roomName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.room_name
     *
     * @param roomName the value for room.room_name
     *
     * @mbggenerated Sat Sep 15 16:03:14 CST 2018
     */
    public void setRoomName(String roomName) {
        this.roomName = roomName == null ? null : roomName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.room_state
     *
     * @return the value of room.room_state
     *
     * @mbggenerated Sat Sep 15 16:03:14 CST 2018
     */
    public String getRoomState() {
        return roomState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.room_state
     *
     * @param roomState the value for room.room_state
     *
     * @mbggenerated Sat Sep 15 16:03:14 CST 2018
     */
    public void setRoomState(String roomState) {
        this.roomState = roomState == null ? null : roomState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.room_create_id
     *
     * @return the value of room.room_create_id
     *
     * @mbggenerated Sat Sep 15 16:03:14 CST 2018
     */
    public Integer getRoomCreateId() {
        return roomCreateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.room_create_id
     *
     * @param roomCreateId the value for room.room_create_id
     *
     * @mbggenerated Sat Sep 15 16:03:14 CST 2018
     */
    public void setRoomCreateId(Integer roomCreateId) {
        this.roomCreateId = roomCreateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.room_create_time
     *
     * @return the value of room.room_create_time
     *
     * @mbggenerated Sat Sep 15 16:03:14 CST 2018
     */
    public Date getRoomCreateTime() {
        return roomCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.room_create_time
     *
     * @param roomCreateTime the value for room.room_create_time
     *
     * @mbggenerated Sat Sep 15 16:03:14 CST 2018
     */
    public void setRoomCreateTime(Date roomCreateTime) {
        this.roomCreateTime = roomCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.room_limit
     *
     * @return the value of room.room_limit
     *
     * @mbggenerated Sat Sep 15 16:03:14 CST 2018
     */
    public Integer getRoomLimit() {
        return roomLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.room_limit
     *
     * @param roomLimit the value for room.room_limit
     *
     * @mbggenerated Sat Sep 15 16:03:14 CST 2018
     */
    public void setRoomLimit(Integer roomLimit) {
        this.roomLimit = roomLimit;
    }
}