package org.bumblebee.entity;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

public class Sigin implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sigin.sigin_id
     *
     * @mbggenerated Tue Sep 25 20:06:45 CST 2018
     */
    private Integer siginId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sigin.sigin_date
     *
     * @mbggenerated Tue Sep 25 20:06:45 CST 2018
     */
    private Date siginDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sigin.sigin_user_id
     *
     * @mbggenerated Tue Sep 25 20:06:45 CST 2018
     */
    private Integer siginUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sigin.sigin_state
     *
     * @mbggenerated Tue Sep 25 20:06:45 CST 2018
     */
    private Integer siginState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sigin.sigin_room_id
     *
     * @mbggenerated Tue Sep 25 20:06:45 CST 2018
     */
    private Integer siginRoomId;

    private List<Sigindetail> sigindetailList;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sigin
     *
     * @mbggenerated Tue Sep 25 20:06:45 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sigin.sigin_id
     *
     * @return the value of sigin.sigin_id
     *
     * @mbggenerated Tue Sep 25 20:06:45 CST 2018
     */
    public Integer getSiginId() {
        return siginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sigin.sigin_id
     *
     * @param siginId the value for sigin.sigin_id
     *
     * @mbggenerated Tue Sep 25 20:06:45 CST 2018
     */
    public void setSiginId(Integer siginId) {
        this.siginId = siginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sigin.sigin_date
     *
     * @return the value of sigin.sigin_date
     *
     * @mbggenerated Tue Sep 25 20:06:45 CST 2018
     */
    public Date getSiginDate() {
        return siginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sigin.sigin_date
     *
     * @param siginDate the value for sigin.sigin_date
     *
     * @mbggenerated Tue Sep 25 20:06:45 CST 2018
     */
    public void setSiginDate(Date siginDate) {
        this.siginDate = siginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sigin.sigin_user_id
     *
     * @return the value of sigin.sigin_user_id
     *
     * @mbggenerated Tue Sep 25 20:06:45 CST 2018
     */
    public Integer getSiginUserId() {
        return siginUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sigin.sigin_user_id
     *
     * @param siginUserId the value for sigin.sigin_user_id
     *
     * @mbggenerated Tue Sep 25 20:06:45 CST 2018
     */
    public void setSiginUserId(Integer siginUserId) {
        this.siginUserId = siginUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sigin.sigin_state
     *
     * @return the value of sigin.sigin_state
     *
     * @mbggenerated Tue Sep 25 20:06:45 CST 2018
     */
    public Integer getSiginState() {
        return siginState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sigin.sigin_state
     *
     * @param siginState the value for sigin.sigin_state
     *
     * @mbggenerated Tue Sep 25 20:06:45 CST 2018
     */
    public void setSiginState(Integer siginState) {
        this.siginState = siginState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sigin.sigin_room_id
     *
     * @return the value of sigin.sigin_room_id
     *
     * @mbggenerated Tue Sep 25 20:06:45 CST 2018
     */
    public Integer getSiginRoomId() {
        return siginRoomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sigin.sigin_room_id
     *
     * @param siginRoomId the value for sigin.sigin_room_id
     *
     * @mbggenerated Tue Sep 25 20:06:45 CST 2018
     */
    public void setSiginRoomId(Integer siginRoomId) {
        this.siginRoomId = siginRoomId;
    }
}