package org.bumblebee.entity;

import java.io.Serializable;

public class Sigindetail implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sigindetail.sd_id
     *
     * @mbggenerated Tue Sep 25 20:06:45 CST 2018
     */
    private Integer sdId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sigindetail.sd_user_id
     *
     * @mbggenerated Tue Sep 25 20:06:45 CST 2018
     */
    private Integer sdUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sigindetail.sd_sigin_id
     *
     * @mbggenerated Tue Sep 25 20:06:45 CST 2018
     */
    private Integer sdSiginId;

    private User user;

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sigindetail
     *
     * @mbggenerated Tue Sep 25 20:06:45 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sigindetail.sd_id
     *
     * @return the value of sigindetail.sd_id
     *
     * @mbggenerated Tue Sep 25 20:06:45 CST 2018
     */
    public Integer getSdId() {
        return sdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sigindetail.sd_id
     *
     * @param sdId the value for sigindetail.sd_id
     *
     * @mbggenerated Tue Sep 25 20:06:45 CST 2018
     */
    public void setSdId(Integer sdId) {
        this.sdId = sdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sigindetail.sd_user_id
     *
     * @return the value of sigindetail.sd_user_id
     *
     * @mbggenerated Tue Sep 25 20:06:45 CST 2018
     */
    public Integer getSdUserId() {
        return sdUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sigindetail.sd_user_id
     *
     * @param sdUserId the value for sigindetail.sd_user_id
     *
     * @mbggenerated Tue Sep 25 20:06:45 CST 2018
     */
    public void setSdUserId(Integer sdUserId) {
        this.sdUserId = sdUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sigindetail.sd_sigin_id
     *
     * @return the value of sigindetail.sd_sigin_id
     *
     * @mbggenerated Tue Sep 25 20:06:45 CST 2018
     */
    public Integer getSdSiginId() {
        return sdSiginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sigindetail.sd_sigin_id
     *
     * @param sdSiginId the value for sigindetail.sd_sigin_id
     *
     * @mbggenerated Tue Sep 25 20:06:45 CST 2018
     */
    public void setSdSiginId(Integer sdSiginId) {
        this.sdSiginId = sdSiginId;
    }
}