package org.bumblebee.entity;

import java.util.ArrayList;
import java.util.List;

public class VoterecordExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table voterecord
     *
     * @mbggenerated Wed Sep 26 10:53:26 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table voterecord
     *
     * @mbggenerated Wed Sep 26 10:53:26 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table voterecord
     *
     * @mbggenerated Wed Sep 26 10:53:26 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table voterecord
     *
     * @mbggenerated Wed Sep 26 10:53:26 CST 2018
     */
    protected Integer limitStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table voterecord
     *
     * @mbggenerated Wed Sep 26 10:53:26 CST 2018
     */
    protected Integer limitEnd;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voterecord
     *
     * @mbggenerated Wed Sep 26 10:53:26 CST 2018
     */
    public VoterecordExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voterecord
     *
     * @mbggenerated Wed Sep 26 10:53:26 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voterecord
     *
     * @mbggenerated Wed Sep 26 10:53:26 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voterecord
     *
     * @mbggenerated Wed Sep 26 10:53:26 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voterecord
     *
     * @mbggenerated Wed Sep 26 10:53:26 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voterecord
     *
     * @mbggenerated Wed Sep 26 10:53:26 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voterecord
     *
     * @mbggenerated Wed Sep 26 10:53:26 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voterecord
     *
     * @mbggenerated Wed Sep 26 10:53:26 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voterecord
     *
     * @mbggenerated Wed Sep 26 10:53:26 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voterecord
     *
     * @mbggenerated Wed Sep 26 10:53:26 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voterecord
     *
     * @mbggenerated Wed Sep 26 10:53:26 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voterecord
     *
     * @mbggenerated Wed Sep 26 10:53:26 CST 2018
     */
    public void setLimitStart(Integer limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voterecord
     *
     * @mbggenerated Wed Sep 26 10:53:26 CST 2018
     */
    public Integer getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voterecord
     *
     * @mbggenerated Wed Sep 26 10:53:26 CST 2018
     */
    public void setLimitEnd(Integer limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voterecord
     *
     * @mbggenerated Wed Sep 26 10:53:26 CST 2018
     */
    public Integer getLimitEnd() {
        return limitEnd;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table voterecord
     *
     * @mbggenerated Wed Sep 26 10:53:26 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andVrIdIsNull() {
            addCriterion("vr_id is null");
            return (Criteria) this;
        }

        public Criteria andVrIdIsNotNull() {
            addCriterion("vr_id is not null");
            return (Criteria) this;
        }

        public Criteria andVrIdEqualTo(Integer value) {
            addCriterion("vr_id =", value, "vrId");
            return (Criteria) this;
        }

        public Criteria andVrIdNotEqualTo(Integer value) {
            addCriterion("vr_id <>", value, "vrId");
            return (Criteria) this;
        }

        public Criteria andVrIdGreaterThan(Integer value) {
            addCriterion("vr_id >", value, "vrId");
            return (Criteria) this;
        }

        public Criteria andVrIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("vr_id >=", value, "vrId");
            return (Criteria) this;
        }

        public Criteria andVrIdLessThan(Integer value) {
            addCriterion("vr_id <", value, "vrId");
            return (Criteria) this;
        }

        public Criteria andVrIdLessThanOrEqualTo(Integer value) {
            addCriterion("vr_id <=", value, "vrId");
            return (Criteria) this;
        }

        public Criteria andVrIdIn(List<Integer> values) {
            addCriterion("vr_id in", values, "vrId");
            return (Criteria) this;
        }

        public Criteria andVrIdNotIn(List<Integer> values) {
            addCriterion("vr_id not in", values, "vrId");
            return (Criteria) this;
        }

        public Criteria andVrIdBetween(Integer value1, Integer value2) {
            addCriterion("vr_id between", value1, value2, "vrId");
            return (Criteria) this;
        }

        public Criteria andVrIdNotBetween(Integer value1, Integer value2) {
            addCriterion("vr_id not between", value1, value2, "vrId");
            return (Criteria) this;
        }

        public Criteria andVrUserIdIsNull() {
            addCriterion("vr_user_id is null");
            return (Criteria) this;
        }

        public Criteria andVrUserIdIsNotNull() {
            addCriterion("vr_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andVrUserIdEqualTo(Integer value) {
            addCriterion("vr_user_id =", value, "vrUserId");
            return (Criteria) this;
        }

        public Criteria andVrUserIdNotEqualTo(Integer value) {
            addCriterion("vr_user_id <>", value, "vrUserId");
            return (Criteria) this;
        }

        public Criteria andVrUserIdGreaterThan(Integer value) {
            addCriterion("vr_user_id >", value, "vrUserId");
            return (Criteria) this;
        }

        public Criteria andVrUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("vr_user_id >=", value, "vrUserId");
            return (Criteria) this;
        }

        public Criteria andVrUserIdLessThan(Integer value) {
            addCriterion("vr_user_id <", value, "vrUserId");
            return (Criteria) this;
        }

        public Criteria andVrUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("vr_user_id <=", value, "vrUserId");
            return (Criteria) this;
        }

        public Criteria andVrUserIdIn(List<Integer> values) {
            addCriterion("vr_user_id in", values, "vrUserId");
            return (Criteria) this;
        }

        public Criteria andVrUserIdNotIn(List<Integer> values) {
            addCriterion("vr_user_id not in", values, "vrUserId");
            return (Criteria) this;
        }

        public Criteria andVrUserIdBetween(Integer value1, Integer value2) {
            addCriterion("vr_user_id between", value1, value2, "vrUserId");
            return (Criteria) this;
        }

        public Criteria andVrUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("vr_user_id not between", value1, value2, "vrUserId");
            return (Criteria) this;
        }

        public Criteria andVrVdIdIsNull() {
            addCriterion("vr_vd_id is null");
            return (Criteria) this;
        }

        public Criteria andVrVdIdIsNotNull() {
            addCriterion("vr_vd_id is not null");
            return (Criteria) this;
        }

        public Criteria andVrVdIdEqualTo(Integer value) {
            addCriterion("vr_vd_id =", value, "vrVdId");
            return (Criteria) this;
        }

        public Criteria andVrVdIdNotEqualTo(Integer value) {
            addCriterion("vr_vd_id <>", value, "vrVdId");
            return (Criteria) this;
        }

        public Criteria andVrVdIdGreaterThan(Integer value) {
            addCriterion("vr_vd_id >", value, "vrVdId");
            return (Criteria) this;
        }

        public Criteria andVrVdIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("vr_vd_id >=", value, "vrVdId");
            return (Criteria) this;
        }

        public Criteria andVrVdIdLessThan(Integer value) {
            addCriterion("vr_vd_id <", value, "vrVdId");
            return (Criteria) this;
        }

        public Criteria andVrVdIdLessThanOrEqualTo(Integer value) {
            addCriterion("vr_vd_id <=", value, "vrVdId");
            return (Criteria) this;
        }

        public Criteria andVrVdIdIn(List<Integer> values) {
            addCriterion("vr_vd_id in", values, "vrVdId");
            return (Criteria) this;
        }

        public Criteria andVrVdIdNotIn(List<Integer> values) {
            addCriterion("vr_vd_id not in", values, "vrVdId");
            return (Criteria) this;
        }

        public Criteria andVrVdIdBetween(Integer value1, Integer value2) {
            addCriterion("vr_vd_id between", value1, value2, "vrVdId");
            return (Criteria) this;
        }

        public Criteria andVrVdIdNotBetween(Integer value1, Integer value2) {
            addCriterion("vr_vd_id not between", value1, value2, "vrVdId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table voterecord
     *
     * @mbggenerated do_not_delete_during_merge Wed Sep 26 10:53:26 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table voterecord
     *
     * @mbggenerated Wed Sep 26 10:53:26 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}