package org.bumblebee.entity;

import java.io.Serializable;

public class Voterecord implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column voterecord.vr_id
     *
     * @mbggenerated Wed Sep 26 10:53:26 CST 2018
     */
    private Integer vrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column voterecord.vr_user_id
     *
     * @mbggenerated Wed Sep 26 10:53:26 CST 2018
     */
    private Integer vrUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column voterecord.vr_vd_id
     *
     * @mbggenerated Wed Sep 26 10:53:26 CST 2018
     */
    private Integer vrVdId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table voterecord
     *
     * @mbggenerated Wed Sep 26 10:53:26 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voterecord.vr_id
     *
     * @return the value of voterecord.vr_id
     *
     * @mbggenerated Wed Sep 26 10:53:26 CST 2018
     */
    public Integer getVrId() {
        return vrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voterecord.vr_id
     *
     * @param vrId the value for voterecord.vr_id
     *
     * @mbggenerated Wed Sep 26 10:53:26 CST 2018
     */
    public void setVrId(Integer vrId) {
        this.vrId = vrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voterecord.vr_user_id
     *
     * @return the value of voterecord.vr_user_id
     *
     * @mbggenerated Wed Sep 26 10:53:26 CST 2018
     */
    public Integer getVrUserId() {
        return vrUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voterecord.vr_user_id
     *
     * @param vrUserId the value for voterecord.vr_user_id
     *
     * @mbggenerated Wed Sep 26 10:53:26 CST 2018
     */
    public void setVrUserId(Integer vrUserId) {
        this.vrUserId = vrUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voterecord.vr_vd_id
     *
     * @return the value of voterecord.vr_vd_id
     *
     * @mbggenerated Wed Sep 26 10:53:26 CST 2018
     */
    public Integer getVrVdId() {
        return vrVdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voterecord.vr_vd_id
     *
     * @param vrVdId the value for voterecord.vr_vd_id
     *
     * @mbggenerated Wed Sep 26 10:53:26 CST 2018
     */
    public void setVrVdId(Integer vrVdId) {
        this.vrVdId = vrVdId;
    }
}