package org.bumblebee.entity;

import java.io.Serializable;

public class Votedetail implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column votedetail.vd_id
     *
     * @mbggenerated Tue Sep 25 20:06:45 CST 2018
     */
    private Integer vdId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column votedetail.vd_item
     *
     * @mbggenerated Tue Sep 25 20:06:45 CST 2018
     */
    private String vdItem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column votedetail.vd_vote_id
     *
     * @mbggenerated Tue Sep 25 20:06:45 CST 2018
     */
    private Integer vdVoteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table votedetail
     *
     * @mbggenerated Tue Sep 25 20:06:45 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column votedetail.vd_id
     *
     * @return the value of votedetail.vd_id
     *
     * @mbggenerated Tue Sep 25 20:06:45 CST 2018
     */
    public Integer getVdId() {
        return vdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column votedetail.vd_id
     *
     * @param vdId the value for votedetail.vd_id
     *
     * @mbggenerated Tue Sep 25 20:06:45 CST 2018
     */
    public void setVdId(Integer vdId) {
        this.vdId = vdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column votedetail.vd_item
     *
     * @return the value of votedetail.vd_item
     *
     * @mbggenerated Tue Sep 25 20:06:45 CST 2018
     */
    public String getVdItem() {
        return vdItem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column votedetail.vd_item
     *
     * @param vdItem the value for votedetail.vd_item
     *
     * @mbggenerated Tue Sep 25 20:06:45 CST 2018
     */
    public void setVdItem(String vdItem) {
        this.vdItem = vdItem == null ? null : vdItem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column votedetail.vd_vote_id
     *
     * @return the value of votedetail.vd_vote_id
     *
     * @mbggenerated Tue Sep 25 20:06:45 CST 2018
     */
    public Integer getVdVoteId() {
        return vdVoteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column votedetail.vd_vote_id
     *
     * @param vdVoteId the value for votedetail.vd_vote_id
     *
     * @mbggenerated Tue Sep 25 20:06:45 CST 2018
     */
    public void setVdVoteId(Integer vdVoteId) {
        this.vdVoteId = vdVoteId;
    }
}