package org.bumblebee.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class VoteExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vote
     *
     * @mbggenerated Wed Sep 26 10:10:02 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vote
     *
     * @mbggenerated Wed Sep 26 10:10:02 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vote
     *
     * @mbggenerated Wed Sep 26 10:10:02 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vote
     *
     * @mbggenerated Wed Sep 26 10:10:03 CST 2018
     */
    protected Integer limitStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vote
     *
     * @mbggenerated Wed Sep 26 10:10:03 CST 2018
     */
    protected Integer limitEnd;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote
     *
     * @mbggenerated Wed Sep 26 10:10:02 CST 2018
     */
    public VoteExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote
     *
     * @mbggenerated Wed Sep 26 10:10:02 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote
     *
     * @mbggenerated Wed Sep 26 10:10:02 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote
     *
     * @mbggenerated Wed Sep 26 10:10:02 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote
     *
     * @mbggenerated Wed Sep 26 10:10:02 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote
     *
     * @mbggenerated Wed Sep 26 10:10:02 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote
     *
     * @mbggenerated Wed Sep 26 10:10:02 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote
     *
     * @mbggenerated Wed Sep 26 10:10:02 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote
     *
     * @mbggenerated Wed Sep 26 10:10:02 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote
     *
     * @mbggenerated Wed Sep 26 10:10:02 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote
     *
     * @mbggenerated Wed Sep 26 10:10:02 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote
     *
     * @mbggenerated Wed Sep 26 10:10:03 CST 2018
     */
    public void setLimitStart(Integer limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote
     *
     * @mbggenerated Wed Sep 26 10:10:03 CST 2018
     */
    public Integer getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote
     *
     * @mbggenerated Wed Sep 26 10:10:03 CST 2018
     */
    public void setLimitEnd(Integer limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote
     *
     * @mbggenerated Wed Sep 26 10:10:03 CST 2018
     */
    public Integer getLimitEnd() {
        return limitEnd;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vote
     *
     * @mbggenerated Wed Sep 26 10:10:02 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andVoteIdIsNull() {
            addCriterion("vote_id is null");
            return (Criteria) this;
        }

        public Criteria andVoteIdIsNotNull() {
            addCriterion("vote_id is not null");
            return (Criteria) this;
        }

        public Criteria andVoteIdEqualTo(Integer value) {
            addCriterion("vote_id =", value, "voteId");
            return (Criteria) this;
        }

        public Criteria andVoteIdNotEqualTo(Integer value) {
            addCriterion("vote_id <>", value, "voteId");
            return (Criteria) this;
        }

        public Criteria andVoteIdGreaterThan(Integer value) {
            addCriterion("vote_id >", value, "voteId");
            return (Criteria) this;
        }

        public Criteria andVoteIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("vote_id >=", value, "voteId");
            return (Criteria) this;
        }

        public Criteria andVoteIdLessThan(Integer value) {
            addCriterion("vote_id <", value, "voteId");
            return (Criteria) this;
        }

        public Criteria andVoteIdLessThanOrEqualTo(Integer value) {
            addCriterion("vote_id <=", value, "voteId");
            return (Criteria) this;
        }

        public Criteria andVoteIdIn(List<Integer> values) {
            addCriterion("vote_id in", values, "voteId");
            return (Criteria) this;
        }

        public Criteria andVoteIdNotIn(List<Integer> values) {
            addCriterion("vote_id not in", values, "voteId");
            return (Criteria) this;
        }

        public Criteria andVoteIdBetween(Integer value1, Integer value2) {
            addCriterion("vote_id between", value1, value2, "voteId");
            return (Criteria) this;
        }

        public Criteria andVoteIdNotBetween(Integer value1, Integer value2) {
            addCriterion("vote_id not between", value1, value2, "voteId");
            return (Criteria) this;
        }

        public Criteria andVoteNameIsNull() {
            addCriterion("vote_name is null");
            return (Criteria) this;
        }

        public Criteria andVoteNameIsNotNull() {
            addCriterion("vote_name is not null");
            return (Criteria) this;
        }

        public Criteria andVoteNameEqualTo(String value) {
            addCriterion("vote_name =", value, "voteName");
            return (Criteria) this;
        }

        public Criteria andVoteNameNotEqualTo(String value) {
            addCriterion("vote_name <>", value, "voteName");
            return (Criteria) this;
        }

        public Criteria andVoteNameGreaterThan(String value) {
            addCriterion("vote_name >", value, "voteName");
            return (Criteria) this;
        }

        public Criteria andVoteNameGreaterThanOrEqualTo(String value) {
            addCriterion("vote_name >=", value, "voteName");
            return (Criteria) this;
        }

        public Criteria andVoteNameLessThan(String value) {
            addCriterion("vote_name <", value, "voteName");
            return (Criteria) this;
        }

        public Criteria andVoteNameLessThanOrEqualTo(String value) {
            addCriterion("vote_name <=", value, "voteName");
            return (Criteria) this;
        }

        public Criteria andVoteNameLike(String value) {
            addCriterion("vote_name like", value, "voteName");
            return (Criteria) this;
        }

        public Criteria andVoteNameNotLike(String value) {
            addCriterion("vote_name not like", value, "voteName");
            return (Criteria) this;
        }

        public Criteria andVoteNameIn(List<String> values) {
            addCriterion("vote_name in", values, "voteName");
            return (Criteria) this;
        }

        public Criteria andVoteNameNotIn(List<String> values) {
            addCriterion("vote_name not in", values, "voteName");
            return (Criteria) this;
        }

        public Criteria andVoteNameBetween(String value1, String value2) {
            addCriterion("vote_name between", value1, value2, "voteName");
            return (Criteria) this;
        }

        public Criteria andVoteNameNotBetween(String value1, String value2) {
            addCriterion("vote_name not between", value1, value2, "voteName");
            return (Criteria) this;
        }

        public Criteria andVoteUserIdIsNull() {
            addCriterion("vote_user_id is null");
            return (Criteria) this;
        }

        public Criteria andVoteUserIdIsNotNull() {
            addCriterion("vote_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andVoteUserIdEqualTo(Integer value) {
            addCriterion("vote_user_id =", value, "voteUserId");
            return (Criteria) this;
        }

        public Criteria andVoteUserIdNotEqualTo(Integer value) {
            addCriterion("vote_user_id <>", value, "voteUserId");
            return (Criteria) this;
        }

        public Criteria andVoteUserIdGreaterThan(Integer value) {
            addCriterion("vote_user_id >", value, "voteUserId");
            return (Criteria) this;
        }

        public Criteria andVoteUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("vote_user_id >=", value, "voteUserId");
            return (Criteria) this;
        }

        public Criteria andVoteUserIdLessThan(Integer value) {
            addCriterion("vote_user_id <", value, "voteUserId");
            return (Criteria) this;
        }

        public Criteria andVoteUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("vote_user_id <=", value, "voteUserId");
            return (Criteria) this;
        }

        public Criteria andVoteUserIdIn(List<Integer> values) {
            addCriterion("vote_user_id in", values, "voteUserId");
            return (Criteria) this;
        }

        public Criteria andVoteUserIdNotIn(List<Integer> values) {
            addCriterion("vote_user_id not in", values, "voteUserId");
            return (Criteria) this;
        }

        public Criteria andVoteUserIdBetween(Integer value1, Integer value2) {
            addCriterion("vote_user_id between", value1, value2, "voteUserId");
            return (Criteria) this;
        }

        public Criteria andVoteUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("vote_user_id not between", value1, value2, "voteUserId");
            return (Criteria) this;
        }

        public Criteria andVoteRoomIdIsNull() {
            addCriterion("vote_room_id is null");
            return (Criteria) this;
        }

        public Criteria andVoteRoomIdIsNotNull() {
            addCriterion("vote_room_id is not null");
            return (Criteria) this;
        }

        public Criteria andVoteRoomIdEqualTo(Integer value) {
            addCriterion("vote_room_id =", value, "voteRoomId");
            return (Criteria) this;
        }

        public Criteria andVoteRoomIdNotEqualTo(Integer value) {
            addCriterion("vote_room_id <>", value, "voteRoomId");
            return (Criteria) this;
        }

        public Criteria andVoteRoomIdGreaterThan(Integer value) {
            addCriterion("vote_room_id >", value, "voteRoomId");
            return (Criteria) this;
        }

        public Criteria andVoteRoomIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("vote_room_id >=", value, "voteRoomId");
            return (Criteria) this;
        }

        public Criteria andVoteRoomIdLessThan(Integer value) {
            addCriterion("vote_room_id <", value, "voteRoomId");
            return (Criteria) this;
        }

        public Criteria andVoteRoomIdLessThanOrEqualTo(Integer value) {
            addCriterion("vote_room_id <=", value, "voteRoomId");
            return (Criteria) this;
        }

        public Criteria andVoteRoomIdIn(List<Integer> values) {
            addCriterion("vote_room_id in", values, "voteRoomId");
            return (Criteria) this;
        }

        public Criteria andVoteRoomIdNotIn(List<Integer> values) {
            addCriterion("vote_room_id not in", values, "voteRoomId");
            return (Criteria) this;
        }

        public Criteria andVoteRoomIdBetween(Integer value1, Integer value2) {
            addCriterion("vote_room_id between", value1, value2, "voteRoomId");
            return (Criteria) this;
        }

        public Criteria andVoteRoomIdNotBetween(Integer value1, Integer value2) {
            addCriterion("vote_room_id not between", value1, value2, "voteRoomId");
            return (Criteria) this;
        }

        public Criteria andVoteStartTimeIsNull() {
            addCriterion("vote_start_time is null");
            return (Criteria) this;
        }

        public Criteria andVoteStartTimeIsNotNull() {
            addCriterion("vote_start_time is not null");
            return (Criteria) this;
        }

        public Criteria andVoteStartTimeEqualTo(Date value) {
            addCriterion("vote_start_time =", value, "voteStartTime");
            return (Criteria) this;
        }

        public Criteria andVoteStartTimeNotEqualTo(Date value) {
            addCriterion("vote_start_time <>", value, "voteStartTime");
            return (Criteria) this;
        }

        public Criteria andVoteStartTimeGreaterThan(Date value) {
            addCriterion("vote_start_time >", value, "voteStartTime");
            return (Criteria) this;
        }

        public Criteria andVoteStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("vote_start_time >=", value, "voteStartTime");
            return (Criteria) this;
        }

        public Criteria andVoteStartTimeLessThan(Date value) {
            addCriterion("vote_start_time <", value, "voteStartTime");
            return (Criteria) this;
        }

        public Criteria andVoteStartTimeLessThanOrEqualTo(Date value) {
            addCriterion("vote_start_time <=", value, "voteStartTime");
            return (Criteria) this;
        }

        public Criteria andVoteStartTimeIn(List<Date> values) {
            addCriterion("vote_start_time in", values, "voteStartTime");
            return (Criteria) this;
        }

        public Criteria andVoteStartTimeNotIn(List<Date> values) {
            addCriterion("vote_start_time not in", values, "voteStartTime");
            return (Criteria) this;
        }

        public Criteria andVoteStartTimeBetween(Date value1, Date value2) {
            addCriterion("vote_start_time between", value1, value2, "voteStartTime");
            return (Criteria) this;
        }

        public Criteria andVoteStartTimeNotBetween(Date value1, Date value2) {
            addCriterion("vote_start_time not between", value1, value2, "voteStartTime");
            return (Criteria) this;
        }

        public Criteria andVoteEndTimeIsNull() {
            addCriterion("vote_end_time is null");
            return (Criteria) this;
        }

        public Criteria andVoteEndTimeIsNotNull() {
            addCriterion("vote_end_time is not null");
            return (Criteria) this;
        }

        public Criteria andVoteEndTimeEqualTo(Date value) {
            addCriterion("vote_end_time =", value, "voteEndTime");
            return (Criteria) this;
        }

        public Criteria andVoteEndTimeNotEqualTo(Date value) {
            addCriterion("vote_end_time <>", value, "voteEndTime");
            return (Criteria) this;
        }

        public Criteria andVoteEndTimeGreaterThan(Date value) {
            addCriterion("vote_end_time >", value, "voteEndTime");
            return (Criteria) this;
        }

        public Criteria andVoteEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("vote_end_time >=", value, "voteEndTime");
            return (Criteria) this;
        }

        public Criteria andVoteEndTimeLessThan(Date value) {
            addCriterion("vote_end_time <", value, "voteEndTime");
            return (Criteria) this;
        }

        public Criteria andVoteEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("vote_end_time <=", value, "voteEndTime");
            return (Criteria) this;
        }

        public Criteria andVoteEndTimeIn(List<Date> values) {
            addCriterion("vote_end_time in", values, "voteEndTime");
            return (Criteria) this;
        }

        public Criteria andVoteEndTimeNotIn(List<Date> values) {
            addCriterion("vote_end_time not in", values, "voteEndTime");
            return (Criteria) this;
        }

        public Criteria andVoteEndTimeBetween(Date value1, Date value2) {
            addCriterion("vote_end_time between", value1, value2, "voteEndTime");
            return (Criteria) this;
        }

        public Criteria andVoteEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("vote_end_time not between", value1, value2, "voteEndTime");
            return (Criteria) this;
        }

        public Criteria andVoteStateIsNull() {
            addCriterion("vote_state is null");
            return (Criteria) this;
        }

        public Criteria andVoteStateIsNotNull() {
            addCriterion("vote_state is not null");
            return (Criteria) this;
        }

        public Criteria andVoteStateEqualTo(Integer value) {
            addCriterion("vote_state =", value, "voteState");
            return (Criteria) this;
        }

        public Criteria andVoteStateNotEqualTo(Integer value) {
            addCriterion("vote_state <>", value, "voteState");
            return (Criteria) this;
        }

        public Criteria andVoteStateGreaterThan(Integer value) {
            addCriterion("vote_state >", value, "voteState");
            return (Criteria) this;
        }

        public Criteria andVoteStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("vote_state >=", value, "voteState");
            return (Criteria) this;
        }

        public Criteria andVoteStateLessThan(Integer value) {
            addCriterion("vote_state <", value, "voteState");
            return (Criteria) this;
        }

        public Criteria andVoteStateLessThanOrEqualTo(Integer value) {
            addCriterion("vote_state <=", value, "voteState");
            return (Criteria) this;
        }

        public Criteria andVoteStateIn(List<Integer> values) {
            addCriterion("vote_state in", values, "voteState");
            return (Criteria) this;
        }

        public Criteria andVoteStateNotIn(List<Integer> values) {
            addCriterion("vote_state not in", values, "voteState");
            return (Criteria) this;
        }

        public Criteria andVoteStateBetween(Integer value1, Integer value2) {
            addCriterion("vote_state between", value1, value2, "voteState");
            return (Criteria) this;
        }

        public Criteria andVoteStateNotBetween(Integer value1, Integer value2) {
            addCriterion("vote_state not between", value1, value2, "voteState");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vote
     *
     * @mbggenerated do_not_delete_during_merge Wed Sep 26 10:10:03 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vote
     *
     * @mbggenerated Wed Sep 26 10:10:03 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}